# Generated by Django 5.0.2 on 2025-06-23 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_testcase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("language", models.CharField(max_length=30)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Wrong Answer", "Wrong Answer"),
                            ("Time Limit Exceeded", "Time Limit Exceeded"),
                            ("Compiler Error", "Compilation Error"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("memory", models.IntegerField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="core.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
