# Generated by Django 5.2.3 on 2025-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="time_limit",
            field=models.FloatField(
                default=2.0, help_text="Time limit in seconds for code execution"
            ),
        ),
    ]
