name: Trigger auto deployment for algozen-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/algozen-backend-AutoDeployTrigger-eac59447-607b-4e86-953a-d56d7bec7dcc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ALGOZENBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ALGOZENBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALGOZENBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}https://github.com/skhavindev/algozen-backend/blob/master
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.ALGOZENBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALGOZENBACKEND_REGISTRY_PASSWORD }}
          containerAppName: algozen-backend
          resourceGroup: NetworkWatcherRG
          imageToBuild: ghcr.io/algozen-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


